spring:
    datasource:
        url: jdbc:mysql://localhost:3306/mwrdph?serverTimezone=Asia/Shanghai&en
        username: root
        password: 123456
    jackson:
        default-property-inclusion: non_null
        property-naming-strategy: SNAKE_CASE
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        serialization:
            write-dates-as-timestamps: false

mybatis:
    configuration:
        map-underscore-to-camel-case: true
    type-handlers-package: cn.edu.sdst.mwrdph.typehandler

logging:
    level:
        cn.edu.sdst.mwrdph.mapper: trace
        cn.edu.sdst.mwrdph.front.mapper: debug
        cn.edu.sdst.mwrdph.admin.mapper: trace
server:
    port: 9090
video:
    server:
        path: http://132.232.23.142
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
